<?php
/**
 * This is an automated class generated by Victheme Generator Plugin
 * For Mapping assets array.
 * @author jason.xie@victheme.com
 */
class VTCore_Timeline_Assets
  extends VTCore_Wordpress_Models_Dot {

  public function __construct($options = array()) {
    $this->options = array (
      'timeline-admin' =>
        array (
          'css' =>
            array (
              'timeline-admin-css' =>
                array (
                  'url' => 'timeline-admin/css/timeline-admin.css',
                  'path' => 'timeline-admin/css/timeline-admin.css',
                ),
            ),
          'js' =>
            array (
              'timeline-admin-js' =>
                array (
                  'url' => 'timeline-admin/js/timeline-admin.js',
                  'path' => 'timeline-admin/js/timeline-admin.js',
                ),
            ),
        ),
      'timeline-front' =>
        array (
          'css' =>
            array (
              'timeline-front-css' =>
                array (
                  'url' => 'timeline-front/css/timeline-front.css',
                  'path' => 'timeline-front/css/timeline-front.css',
                ),
            ),
          'js' =>
            array (
              'timeline-front-js' =>
                array (
                  'url' => 'timeline-front/js/timeline-front.js',
                  'path' => 'timeline-front/js/timeline-front.js',
                ),
            ),
        ),
      'timeline-skins' =>
        array (
          'css' =>
            array (
              'timeline-skins-css' =>
                array (
                  'url' => 'timeline-skins/css/timeline-skins.css',
                  'path' => 'timeline-skins/css/timeline-skins.css',
                ),
            ),
        ),
    );

  }
}

