<?php
/**
 * This is an automated class generated by Victheme Generator Plugin
 * For Mapping assets array.
 * @author jason.xie@victheme.com
 */
class VTCore_SnakeLine_Assets
  extends VTCore_Wordpress_Models_Dot {

  public function __construct($options = array()) {
    $this->options = array (
      'jquery-snakeline' =>
        array (
          'js' =>
            array (
              'jquery-snakeline-js' =>
                array (
                  'url' => 'jquery-snakeline/js/jquery-snakeline.js',
                  'path' => 'jquery-snakeline/js/jquery-snakeline.js',
                ),
            ),
        ),
      'snakeline-admin' =>
        array (
          'css' =>
            array (
              'snakeline-admin-css' =>
                array (
                  'url' => 'snakeline-admin/css/snakeline-admin.css',
                  'path' => 'snakeline-admin/css/snakeline-admin.css',
                ),
            ),
          'js' =>
            array (
              'snakeline-admin-js' =>
                array (
                  'url' => 'snakeline-admin/js/snakeline-admin.js',
                  'path' => 'snakeline-admin/js/snakeline-admin.js',
                ),
            ),
        ),
      'snakeline-front' =>
        array (
          'css' =>
            array (
              'snakeline-front-css' =>
                array (
                  'url' => 'snakeline-front/css/snakeline-front.css',
                  'path' => 'snakeline-front/css/snakeline-front.css',
                ),
            ),
        ),
    );

  }
}

