<?php
/**
 * This is an automated class generated by Victheme Generator Plugin
 * For Mapping assets array.
 * @author jason.xie@victheme.com
 */
class VTCore_History_Assets
  extends VTCore_Wordpress_Models_Dot {

  public function __construct($options = array()) {
    $this->options = array (
      'history-admin' =>
        array (
          'css' =>
            array (
              'history-admin-css' =>
                array (
                  'url' => 'history-admin/css/history-admin.css',
                  'path' => 'history-admin/css/history-admin.css',
                ),
            ),
          'js' =>
            array (
              'history-admin-js' =>
                array (
                  'url' => 'history-admin/js/history-admin.js',
                  'path' => 'history-admin/js/history-admin.js',
                ),
            ),
        ),
      'history-front' =>
        array (
          'css' =>
            array (
              'history-front-css' =>
                array (
                  'url' => 'history-front/css/history-front.css',
                  'path' => 'history-front/css/history-front.css',
                ),
            ),
        ),
      'jquery-pointconnector' =>
        array (
          'js' =>
            array (
              'jquery-pointconnector-js' =>
                array (
                  'url' => 'jquery-pointconnector/js/jquery-pointconnector.js',
                  'path' => 'jquery-pointconnector/js/jquery-pointconnector.js',
                ),
            ),
        ),
    );

  }
}

