<?php
/**
 * This is an automated class generated by Victheme Generator Plugin
 * For Mapping assets array.
 * @author jason.xie@victheme.com
 */
class VTCore_BubbleLine_Assets
  extends VTCore_Wordpress_Models_Dot {

  public function __construct($options = array()) {
    $this->options = array (
      'bubbleline-admin' =>
        array (
          'css' =>
            array (
              'bubbleline-admin-css' =>
                array (
                  'url' => 'bubbleline-admin/css/bubbleline-admin.css',
                  'path' => 'bubbleline-admin/css/bubbleline-admin.css',
                ),
            ),
          'js' =>
            array (
              'bubbleline-admin-js' =>
                array (
                  'url' => 'bubbleline-admin/js/bubbleline-admin.js',
                  'path' => 'bubbleline-admin/js/bubbleline-admin.js',
                ),
            ),
        ),
      'bubbleline-front' =>
        array (
          'css' =>
            array (
              'bubbleline-front-css' =>
                array (
                  'url' => 'bubbleline-front/css/bubbleline-front.css',
                  'path' => 'bubbleline-front/css/bubbleline-front.css',
                ),
            ),
        ),
      'jquery-bubbleline' =>
        array (
          'js' =>
            array (
              'jquery-bubbleline-js' =>
                array (
                  'url' => 'jquery-bubbleline/js/jquery-bubbleline.js',
                  'path' => 'jquery-bubbleline/js/jquery-bubbleline.js',
                ),
            ),
        ),
    );

  }
}

