<?php
/**
 * This is an automated class generated by Victheme Generator Plugin
 * For Mapping assets array.
 * @author jason.xie@victheme.com
 */
class VTCore_CenterLine_Assets
  extends VTCore_Wordpress_Models_Dot {

  public function __construct($options = array()) {
    $this->options = array (
      'centerline-admin' =>
        array (
          'css' =>
            array (
              'centerline-admin-css' =>
                array (
                  'url' => 'centerline-admin/css/centerline-admin.css',
                  'path' => 'centerline-admin/css/centerline-admin.css',
                ),
            ),
          'js' =>
            array (
              'centerline-admin-js' =>
                array (
                  'url' => 'centerline-admin/js/centerline-admin.js',
                  'path' => 'centerline-admin/js/centerline-admin.js',
                ),
            ),
        ),
      'centerline-front' =>
        array (
          'css' =>
            array (
              'centerline-front-css' =>
                array (
                  'url' => 'centerline-front/css/centerline-front.css',
                  'path' => 'centerline-front/css/centerline-front.css',
                ),
            ),
        ),
      'jquery-centerline' =>
        array (
          'js' =>
            array (
              'jquery-centerline-js' =>
                array (
                  'url' => 'jquery-centerline/js/jquery-centerline.js',
                  'path' => 'jquery-centerline/js/jquery-centerline.js',
                ),
            ),
        ),
    );

  }
}

