<?php
/**
 * This is an automated class generated by Victheme Generator Plugin
 * For Mapping assets array.
 * @author jason.xie@victheme.com
 */
class VTCore_MemoryLine_Assets
  extends VTCore_Wordpress_Models_Dot {

  public function __construct($options = array()) {
    $this->options = array (
      'jquery-memoryline' =>
        array (
          'js' =>
            array (
              'jquery-memoryline-js' =>
                array (
                  'url' => 'jquery-memoryline/js/jquery-memoryline.js',
                  'path' => 'jquery-memoryline/js/jquery-memoryline.js',
                ),
            ),
        ),
      'memoryline-admin' =>
        array (
          'css' =>
            array (
              'memoryline-admin-css' =>
                array (
                  'url' => 'memoryline-admin/css/memoryline-admin.css',
                  'path' => 'memoryline-admin/css/memoryline-admin.css',
                ),
            ),
          'js' =>
            array (
              'memoryline-admin-js' =>
                array (
                  'url' => 'memoryline-admin/js/memoryline-admin.js',
                  'path' => 'memoryline-admin/js/memoryline-admin.js',
                ),
            ),
        ),
      'memoryline-front' =>
        array (
          'css' =>
            array (
              'memoryline-front-css' =>
                array (
                  'url' => 'memoryline-front/css/memoryline-front.css',
                  'path' => 'memoryline-front/css/memoryline-front.css',
                ),
            ),
        ),
    );

  }
}

