<?php
/**
 * This is an automated class generated by Victheme Generator Plugin
 * For Mapping assets array.
 * @author jason.xie@victheme.com
 */
class VTCore_Wordpress_Data_Maps_Core
  extends VTCore_Wordpress_Models_Dot {

  public function __construct($options = array()) {
    $this->options = array (
      'bootstrap' =>
        array (
          'css' =>
            array (
              'bootstrap-theme-css' =>
                array (
                  'url' => 'bootstrap/css/bootstrap-theme.css',
                  'path' => 'bootstrap/css/bootstrap-theme.css',
                ),
              'bootstrap-css' =>
                array (
                  'url' => 'bootstrap/css/bootstrap.css',
                  'path' => 'bootstrap/css/bootstrap.css',
                ),
            ),
          'js' =>
            array (
              'bootstrap-js' =>
                array (
                  'url' => 'bootstrap/js/bootstrap.js',
                  'path' => 'bootstrap/js/bootstrap.js',
                ),
            ),
        ),
      'bootstrap-clockpicker' =>
        array (
          'css' =>
            array (
              'bootstrap-clockpicker-css' =>
                array (
                  'url' => 'bootstrap-clockpicker/css/bootstrap-clockpicker.css',
                  'path' => 'bootstrap-clockpicker/css/bootstrap-clockpicker.css',
                ),
            ),
          'js' =>
            array (
              'bootstrap-clockpicker-js' =>
                array (
                  'url' => 'bootstrap-clockpicker/js/bootstrap-clockpicker.js',
                  'path' => 'bootstrap-clockpicker/js/bootstrap-clockpicker.js',
                ),
            ),
        ),
      'bootstrap-colorpicker' =>
        array (
          'css' =>
            array (
              'bootstrap-colorpicker-css' =>
                array (
                  'url' => 'bootstrap-colorpicker/css/bootstrap-colorpicker.css',
                  'path' => 'bootstrap-colorpicker/css/bootstrap-colorpicker.css',
                ),
            ),
          'js' =>
            array (
              'bootstrap-colorpicker-js' =>
                array (
                  'url' => 'bootstrap-colorpicker/js/bootstrap-colorpicker.js',
                  'path' => 'bootstrap-colorpicker/js/bootstrap-colorpicker.js',
                ),
            ),
        ),
      'bootstrap-confirmation' =>
        array (
          'js' =>
            array (
              'bootstrap-confirmation-js' =>
                array (
                  'url' => 'bootstrap-confirmation/js/bootstrap-confirmation.js',
                  'path' => 'bootstrap-confirmation/js/bootstrap-confirmation.js',
                ),
            ),
        ),
      'bootstrap-datepicker' =>
        array (
          'css' =>
            array (
              'bootstrap-datepicker-css' =>
                array (
                  'url' => 'bootstrap-datepicker/css/bootstrap-datepicker.css',
                  'path' => 'bootstrap-datepicker/css/bootstrap-datepicker.css',
                ),
            ),
          'js' =>
            array (
              'bootstrap-datepicker-js' =>
                array (
                  'url' => 'bootstrap-datepicker/js/bootstrap-datepicker.js',
                  'path' => 'bootstrap-datepicker/js/bootstrap-datepicker.js',
                ),
            ),
        ),
      'bootstrap-dependency-toggle' =>
        array (
          'js' =>
            array (
              'bootstrap-dependency-toggle-js' =>
                array (
                  'url' => 'bootstrap-dependency-toggle/js/bootstrap-dependency-toggle.js',
                  'path' => 'bootstrap-dependency-toggle/js/bootstrap-dependency-toggle.js',
                ),
            ),
        ),
      'bootstrap-form-only' =>
        array (
          'css' =>
            array (
              'bootstrap-form-only-css' =>
                array (
                  'url' => 'bootstrap-form-only/css/bootstrap-form-only.css',
                  'path' => 'bootstrap-form-only/css/bootstrap-form-only.css',
                ),
            ),
        ),
      'bootstrap-glyphicon' =>
        array (
          'css' =>
            array (
              'bootstrap-css' =>
                array (
                  'url' => 'bootstrap-glyphicon/css/bootstrap.css',
                  'path' => 'bootstrap-glyphicon/css/bootstrap.css',
                ),
            ),
        ),
      'bootstrap-grid-only' =>
        array (
          'css' =>
            array (
              'bootstrap-grid-only-css' =>
                array (
                  'url' => 'bootstrap-grid-only/css/bootstrap-grid-only.css',
                  'path' => 'bootstrap-grid-only/css/bootstrap-grid-only.css',
                ),
            ),
        ),
      'bootstrap-grids' =>
        array (
          'css' =>
            array (
              'bootstrap-grids-css' =>
                array (
                  'url' => 'bootstrap-grids/css/bootstrap-grids.css',
                  'path' => 'bootstrap-grids/css/bootstrap-grids.css',
                ),
            ),
        ),
      'bootstrap-image-gallery' =>
        array (
          'css' =>
            array (
              'bootstrap-image-gallery-css' =>
                array (
                  'url' => 'bootstrap-image-gallery/css/bootstrap-image-gallery.css',
                  'path' => 'bootstrap-image-gallery/css/bootstrap-image-gallery.css',
                ),
            ),
          'js' =>
            array (
              'bootstrap-image-gallery-js' =>
                array (
                  'url' => 'bootstrap-image-gallery/js/bootstrap-image-gallery.js',
                  'path' => 'bootstrap-image-gallery/js/bootstrap-image-gallery.js',
                ),
            ),
        ),
      'bootstrap-password' =>
        array (
          'css' =>
            array (
              'bootstrap-password-css' =>
                array (
                  'url' => 'bootstrap-password/css/bootstrap-password.css',
                  'path' => 'bootstrap-password/css/bootstrap-password.css',
                ),
            ),
          'js' =>
            array (
              'bootstrap-password-js' =>
                array (
                  'url' => 'bootstrap-password/js/bootstrap-password.js',
                  'path' => 'bootstrap-password/js/bootstrap-password.js',
                ),
            ),
        ),
      'bootstrap-range' =>
        array (
          'css' =>
            array (
              'bootstrap-range-css' =>
                array (
                  'url' => 'bootstrap-range/css/bootstrap-range.css',
                  'path' => 'bootstrap-range/css/bootstrap-range.css',
                ),
            ),
          'js' =>
            array (
              'bootstrap-range-js' =>
                array (
                  'url' => 'bootstrap-range/js/bootstrap-range.js',
                  'path' => 'bootstrap-range/js/bootstrap-range.js',
                ),
            ),
        ),
      'bootstrap-select' =>
        array (
          'css' =>
            array (
              'bootstrap-select-css' =>
                array (
                  'url' => 'bootstrap-select/css/bootstrap-select.css',
                  'path' => 'bootstrap-select/css/bootstrap-select.css',
                ),
            ),
          'js' =>
            array (
              'bootstrap-select-js' =>
                array (
                  'url' => 'bootstrap-select/js/bootstrap-select.js',
                  'path' => 'bootstrap-select/js/bootstrap-select.js',
                ),
            ),
        ),
      'bootstrap-spinner' =>
        array (
          'css' =>
            array (
              'bootstrap-spinner-css' =>
                array (
                  'url' => 'bootstrap-spinner/css/bootstrap-spinner.css',
                  'path' => 'bootstrap-spinner/css/bootstrap-spinner.css',
                ),
            ),
        ),
      'bootstrap-switch' =>
        array (
          'css' =>
            array (
              'bootstrap-switch-css' =>
                array (
                  'url' => 'bootstrap-switch/css/bootstrap-switch.css',
                  'path' => 'bootstrap-switch/css/bootstrap-switch.css',
                ),
            ),
        ),
      'bootstrap-toggle-label' =>
        array (
          'css' =>
            array (
              'bootstrap-toggle-label-css' =>
                array (
                  'url' => 'bootstrap-toggle-label/css/bootstrap-toggle-label.css',
                  'path' => 'bootstrap-toggle-label/css/bootstrap-toggle-label.css',
                ),
            ),
          'js' =>
            array (
              'bootstrap-toggle-label-js' =>
                array (
                  'url' => 'bootstrap-toggle-label/js/bootstrap-toggle-label.js',
                  'path' => 'bootstrap-toggle-label/js/bootstrap-toggle-label.js',
                ),
            ),
        ),
      'css-animation' =>
        array (
          'css' =>
            array (
              'animate-css' =>
                array (
                  'url' => 'css-animation/css/animate.css',
                  'path' => 'css-animation/css/animate.css',
                ),
            ),
        ),
      'font-awesome' =>
        array (
          'css' =>
            array (
              'font-awesome-min-css' =>
                array (
                  'url' => 'font-awesome/css/font-awesome.min.css',
                  'path' => 'font-awesome/css/font-awesome.min.css',
                ),
              'fontawesome-plus-css' =>
                array (
                  'url' => 'font-awesome/css/fontawesome-plus.css',
                  'path' => 'font-awesome/css/fontawesome-plus.css',
                ),
            ),
        ),
      'icon-eleganticon' =>
        array (
          'css' =>
            array (
              'icon-eleganticon-css' =>
                array (
                  'url' => 'icon-eleganticon/css/icon-eleganticon.css',
                  'path' => 'icon-eleganticon/css/icon-eleganticon.css',
                ),
            ),
        ),
      'icon-entypo' =>
        array (
          'css' =>
            array (
              'icon-entypo-css' =>
                array (
                  'url' => 'icon-entypo/css/icon-entypo.css',
                  'path' => 'icon-entypo/css/icon-entypo.css',
                ),
            ),
        ),
      'icon-foundation' =>
        array (
          'css' =>
            array (
              'icon-foundation-css' =>
                array (
                  'url' => 'icon-foundation/css/icon-foundation.css',
                  'path' => 'icon-foundation/css/icon-foundation.css',
                ),
            ),
        ),
      'icon-open-iconic' =>
        array (
          'css' =>
            array (
              'icon-open-iconic-css' =>
                array (
                  'url' => 'icon-open-iconic/css/icon-open-iconic.css',
                  'path' => 'icon-open-iconic/css/icon-open-iconic.css',
                ),
            ),
        ),
      'icon-typicons' =>
        array (
          'css' =>
            array (
              'icon-typicons-css' =>
                array (
                  'url' => 'icon-typicons/css/icon-typicons.css',
                  'path' => 'icon-typicons/css/icon-typicons.css',
                ),
            ),
        ),
      'jquery-animsition' =>
        array (
          'css' =>
            array (
              'animsition-min-css' =>
                array (
                  'url' => 'jquery-animsition/css/animsition.min.css',
                  'path' => 'jquery-animsition/css/animsition.min.css',
                ),
            ),
          'js' =>
            array (
              'animsition-js' =>
                array (
                  'url' => 'jquery-animsition/js/animsition.js',
                  'path' => 'jquery-animsition/js/animsition.js',
                ),
            ),
        ),
      'jquery-aspect-ratio' =>
        array (
          'js' =>
            array (
              'aspect-ratio-js' =>
                array (
                  'url' => 'jquery-aspect-ratio/js/aspect-ratio.js',
                  'path' => 'jquery-aspect-ratio/js/aspect-ratio.js',
                ),
            ),
        ),
      'jquery-custom-scrollbar' =>
        array (
          'css' =>
            array (
              'jquery-custom-scrollbar-css' =>
                array (
                  'url' => 'jquery-custom-scrollbar/css/jquery.custom-scrollbar.css',
                  'path' => 'jquery-custom-scrollbar/css/jquery.custom-scrollbar.css',
                ),
            ),
          'js' =>
            array (
              'jquery-custom-scrollbar-js' =>
                array (
                  'url' => 'jquery-custom-scrollbar/js/jquery.custom-scrollbar.js',
                  'path' => 'jquery-custom-scrollbar/js/jquery.custom-scrollbar.js',
                ),
            ),
        ),
      'jquery-deparam' =>
        array (
          'js' =>
            array (
              'jquery-deparam-min-js' =>
                array (
                  'url' => 'jquery-deparam/js/jquery-deparam.min.js',
                  'path' => 'jquery-deparam/js/jquery-deparam.min.js',
                ),
            ),
        ),
      'jquery-directional-hover' =>
        array (
          'css' =>
            array (
              'jquery-hover-dir-css' =>
                array (
                  'url' => 'jquery-directional-hover/css/jquery.hover.dir.css',
                  'path' => 'jquery-directional-hover/css/jquery.hover.dir.css',
                ),
            ),
          'js' =>
            array (
              'jquery-hoverdir-js' =>
                array (
                  'url' => 'jquery-directional-hover/js/jquery.hoverdir.js',
                  'path' => 'jquery-directional-hover/js/jquery.hoverdir.js',
                ),
            ),
        ),
      'jquery-easing' =>
        array (
          'js' =>
            array (
              'jquery-easing-1-3-min-js' =>
                array (
                  'url' => 'jquery-easing/js/jquery.easing.1.3.min.js',
                  'path' => 'jquery-easing/js/jquery.easing.1.3.min.js',
                ),
            ),
        ),
      'jquery-equalheight' =>
        array (
          'js' =>
            array (
              'jquery-equalheight-row-js' =>
                array (
                  'url' => 'jquery-equalheight/js/jquery.equalheight.row.js',
                  'path' => 'jquery-equalheight/js/jquery.equalheight.row.js',
                ),
            ),
        ),
      'jquery-fitcontainer' =>
        array (
          'js' =>
            array (
              'jquery-fitcontainer-js' =>
                array (
                  'url' => 'jquery-fitcontainer/js/jquery-fitcontainer.js',
                  'path' => 'jquery-fitcontainer/js/jquery-fitcontainer.js',
                ),
            ),
        ),
      'jquery-fittext' =>
        array (
          'js' =>
            array (
              'jquery-fittext-js' =>
                array (
                  'url' => 'jquery-fittext/js/jquery.fittext.js',
                  'path' => 'jquery-fittext/js/jquery.fittext.js',
                ),
            ),
        ),
      'jquery-flip' =>
        array (
          'js' =>
            array (
              'jquery-flip-js' =>
                array (
                  'url' => 'jquery-flip/js/jquery.flip.js',
                  'path' => 'jquery-flip/js/jquery.flip.js',
                ),
            ),
        ),
      'jquery-hcsticky' =>
        array (
          'js' =>
            array (
              'jquery-hcsticky-js' =>
                array (
                  'url' => 'jquery-hcsticky/js/jquery.hcsticky.js',
                  'path' => 'jquery-hcsticky/js/jquery.hcsticky.js',
                ),
            ),
        ),
      'jquery-iconpicker' =>
        array (
          'css' =>
            array (
              'jquery-iconpicker-css' =>
                array (
                  'url' => 'jquery-iconpicker/css/jquery-iconpicker.css',
                  'path' => 'jquery-iconpicker/css/jquery-iconpicker.css',
                ),
            ),
          'js' =>
            array (
              'jquery-iconpicker-js' =>
                array (
                  'url' => 'jquery-iconpicker/js/jquery-iconpicker.js',
                  'path' => 'jquery-iconpicker/js/jquery-iconpicker.js',
                ),
            ),
        ),
      'jquery-imgliquid' =>
        array (
          'js' =>
            array (
              'imgLiquid-min-js' =>
                array (
                  'url' => 'jquery-imgliquid/js/imgLiquid-min.js',
                  'path' => 'jquery-imgliquid/js/imgLiquid-min.js',
                ),
            ),
        ),
      'jquery-isotope' =>
        array (
          'js' =>
            array (
              'jquery-isotope-js' =>
                array (
                  'url' => 'jquery-isotope/js/jquery.isotope.js',
                  'path' => 'jquery-isotope/js/jquery.isotope.js',
                ),
            ),
        ),
      'jquery-lazyliner' =>
        array (
          'js' =>
            array (
              'lazylinepainter-js' =>
                array (
                  'url' => 'jquery-lazyliner/js/lazylinepainter.js',
                  'path' => 'jquery-lazyliner/js/lazylinepainter.js',
                ),
            ),
        ),
      'jquery-move' =>
        array (
          'js' =>
            array (
              'jquery-event-move-js' =>
                array (
                  'url' => 'jquery-move/js/jquery.event.move.js',
                  'path' => 'jquery-move/js/jquery.event.move.js',
                ),
              'jquery-event-swipe-js' =>
                array (
                  'url' => 'jquery-move/js/jquery.event.swipe.js',
                  'path' => 'jquery-move/js/jquery.event.swipe.js',
                ),
            ),
        ),
      'jquery-nicescroll' =>
        array (
          'js' =>
            array (
              'jquery-nicescroll-js' =>
                array (
                  'url' => 'jquery-nicescroll/js/jquery.nicescroll.js',
                  'path' => 'jquery-nicescroll/js/jquery.nicescroll.js',
                ),
            ),
        ),
      'jquery-nouislider' =>
        array (
          'css' =>
            array (
              'nouislider-min-css' =>
                array (
                  'url' => 'jquery-nouislider/css/nouislider.min.css',
                  'path' => 'jquery-nouislider/css/nouislider.min.css',
                ),
            ),
          'js' =>
            array (
              'nouislider-js' =>
                array (
                  'url' => 'jquery-nouislider/js/nouislider.js',
                  'path' => 'jquery-nouislider/js/nouislider.js',
                ),
            ),
        ),
      'jquery-parallax' =>
        array (
          'js' =>
            array (
              'jquery-parallax-js' =>
                array (
                  'url' => 'jquery-parallax/js/jquery-parallax.js',
                  'path' => 'jquery-parallax/js/jquery-parallax.js',
                ),
            ),
        ),
      'jquery-pycs-layout' =>
        array (
          'js' =>
            array (
              'jquery-pycs-layout-js' =>
                array (
                  'url' => 'jquery-pycs-layout/js/jquery-pycs-layout.js',
                  'path' => 'jquery-pycs-layout/js/jquery-pycs-layout.js',
                ),
            ),
        ),
      'jquery-queryobject' =>
        array (
          'js' =>
            array (
              'jquery-query-object-js' =>
                array (
                  'url' => 'jquery-queryobject/js/jquery.query-object.js',
                  'path' => 'jquery-queryobject/js/jquery.query-object.js',
                ),
            ),
        ),
      'jquery-random-color' =>
        array (
          'js' =>
            array (
              'randomColor-js' =>
                array (
                  'url' => 'jquery-random-color/js/randomColor.js',
                  'path' => 'jquery-random-color/js/randomColor.js',
                ),
            ),
        ),
      'jquery-raty' =>
        array (
          'css' =>
            array (
              'jquery-raty-css' =>
                array (
                  'url' => 'jquery-raty/css/jquery.raty.css',
                  'path' => 'jquery-raty/css/jquery.raty.css',
                ),
            ),
          'js' =>
            array (
              'jquery-raty-js' =>
                array (
                  'url' => 'jquery-raty/js/jquery.raty.js',
                  'path' => 'jquery-raty/js/jquery.raty.js',
                ),
            ),
        ),
      'jquery-real-shadow' =>
        array (
          'js' =>
            array (
              'realshadow-js' =>
                array (
                  'url' => 'jquery-real-shadow/js/realshadow.js',
                  'path' => 'jquery-real-shadow/js/realshadow.js',
                ),
            ),
        ),
      'jquery-resizeend' =>
        array (
          'js' =>
            array (
              'jquery-resizeevents-min-js' =>
                array (
                  'url' => 'jquery-resizeend/js/jquery.resizeevents.min.js',
                  'path' => 'jquery-resizeend/js/jquery.resizeevents.min.js',
                ),
            ),
        ),
      'jquery-retina' =>
        array (
          'js' =>
            array (
              'retina-js' =>
                array (
                  'url' => 'jquery-retina/js/retina.js',
                  'path' => 'jquery-retina/js/retina.js',
                ),
            ),
        ),
      'jquery-slick' =>
        array (
          'css' =>
            array (
              'slick-skins-css' =>
                array (
                  'url' => 'jquery-slick/css/slick-skins.css',
                  'path' => 'jquery-slick/css/slick-skins.css',
                ),
              'slick-css' =>
                array (
                  'url' => 'jquery-slick/css/slick.css',
                  'path' => 'jquery-slick/css/slick.css',
                ),
            ),
          'js' =>
            array (
              'slick-custom-js' =>
                array (
                  'url' => 'jquery-slick/js/slick-custom.js',
                  'path' => 'jquery-slick/js/slick-custom.js',
                ),
            ),
        ),
      'jquery-slicknav' =>
        array (
          'css' =>
            array (
              'slicknav-min-css' =>
                array (
                  'url' => 'jquery-slicknav/css/slicknav.min.css',
                  'path' => 'jquery-slicknav/css/slicknav.min.css',
                ),
            ),
          'js' =>
            array (
              'jquery-slicknav-js' =>
                array (
                  'url' => 'jquery-slicknav/js/jquery.slicknav.js',
                  'path' => 'jquery-slicknav/js/jquery.slicknav.js',
                ),
            ),
        ),
      'jquery-snapscroll' =>
        array (
          'js' =>
            array (
              'jquery-snapscroll-js' =>
                array (
                  'url' => 'jquery-snapscroll/js/jquery.snapscroll.js',
                  'path' => 'jquery-snapscroll/js/jquery.snapscroll.js',
                ),
            ),
        ),
      'jquery-spin' =>
        array (
          'js' =>
            array (
              'jquery-spin-js' =>
                array (
                  'url' => 'jquery-spin/js/jquery-spin.js',
                  'path' => 'jquery-spin/js/jquery-spin.js',
                ),
            ),
        ),
      'jquery-spinner' =>
        array (
          'js' =>
            array (
              'jquery-spinner-js' =>
                array (
                  'url' => 'jquery-spinner/js/jquery.spinner.js',
                  'path' => 'jquery-spinner/js/jquery.spinner.js',
                ),
            ),
        ),
      'jquery-stickyem' =>
        array (
          'js' =>
            array (
              'jquery-stickem-js' =>
                array (
                  'url' => 'jquery-stickyem/js/jquery.stickem.js',
                  'path' => 'jquery-stickyem/js/jquery.stickem.js',
                ),
            ),
        ),
      'jquery-table-manager' =>
        array (
          'css' =>
            array (
              'jquery-tablemanager-css' =>
                array (
                  'url' => 'jquery-table-manager/css/jquery-tablemanager.css',
                  'path' => 'jquery-table-manager/css/jquery-tablemanager.css',
                ),
            ),
          'js' =>
            array (
              'jquery-tablemanager-js' =>
                array (
                  'url' => 'jquery-table-manager/js/jquery-tablemanager.js',
                  'path' => 'jquery-table-manager/js/jquery-tablemanager.js',
                ),
            ),
        ),
      'jquery-texttailor' =>
        array (
          'js' =>
            array (
              'jquery-texttailor-js' =>
                array (
                  'url' => 'jquery-texttailor/js/jquery.texttailor.js',
                  'path' => 'jquery-texttailor/js/jquery.texttailor.js',
                ),
            ),
        ),
      'jquery-timers' =>
        array (
          'js' =>
            array (
              'jquery-timers-1-2-min-js' =>
                array (
                  'url' => 'jquery-timers/js/jquery.timers-1.2.min.js',
                  'path' => 'jquery-timers/js/jquery.timers-1.2.min.js',
                ),
            ),
        ),
      'jquery-totop' =>
        array (
          'css' =>
            array (
              'jquery-ui-totop-min-css' =>
                array (
                  'url' => 'jquery-totop/css/jquery.ui.totop.min.css',
                  'path' => 'jquery-totop/css/jquery.ui.totop.min.css',
                ),
            ),
          'js' =>
            array (
              'jquery-ui-totop-min-js' =>
                array (
                  'url' => 'jquery-totop/js/jquery.ui.totop.min.js',
                  'path' => 'jquery-totop/js/jquery.ui.totop.min.js',
                ),
            ),
        ),
      'jquery-verticalcenter' =>
        array (
          'js' =>
            array (
              'jquery-verticalcenter-js' =>
                array (
                  'url' => 'jquery-verticalcenter/js/jquery.verticalcenter.js',
                  'path' => 'jquery-verticalcenter/js/jquery.verticalcenter.js',
                ),
            ),
        ),
      'jquery-viewport' =>
        array (
          'js' =>
            array (
              'jquery-viewport-js' =>
                array (
                  'url' => 'jquery-viewport/js/jquery.viewport.js',
                  'path' => 'jquery-viewport/js/jquery.viewport.js',
                ),
            ),
        ),
      'jquery-waypoint' =>
        array (
          'js' =>
            array (
              'jquery-waypoints-js' =>
                array (
                  'url' => 'jquery-waypoint/js/jquery.waypoints.js',
                  'path' => 'jquery-waypoint/js/jquery.waypoints.js',
                ),
            ),
        ),
      'js-html2canvas' =>
        array (
          'js' =>
            array (
              'html2canvas-js' =>
                array (
                  'url' => 'js-html2canvas/js/html2canvas.js',
                  'path' => 'js-html2canvas/js/html2canvas.js',
                ),
            ),
        ),
      'js-jspdf' =>
        array (
          'js' =>
            array (
              'jspdf-js' =>
                array (
                  'url' => 'js-jspdf/js/jspdf.js',
                  'path' => 'js-jspdf/js/jspdf.js',
                ),
            ),
        ),
      'js-lazysizes' =>
        array (
          'js' =>
            array (
              'lazysizes-js' =>
                array (
                  'url' => 'js-lazysizes/js/lazysizes.js',
                  'path' => 'js-lazysizes/js/lazysizes.js',
                ),
            ),
        ),
      'js-raphael' =>
        array (
          'js' =>
            array (
              'raphael-min-js' =>
                array (
                  'url' => 'js-raphael/js/raphael.min.js',
                  'path' => 'js-raphael/js/raphael.min.js',
                ),
            ),
        ),
    );

  }
}

