<?php
/**
 * This is an automated class generated by Victheme Generator Plugin
 * For Mapping assets array.
 * @author jason.xie@victheme.com
 */
class VTCore_Wordpress_Data_Maps_Wordpress
  extends VTCore_Wordpress_Models_Dot {

  public function __construct($options = array()) {
    $this->options = array (
      'wp-ajax' =>
        array (
          'js' =>
            array (
              'wp-ajax-js' =>
                array (
                  'url' => 'wp-ajax/js/wp-ajax.js',
                  'path' => 'wp-ajax/js/wp-ajax.js',
                ),
            ),
        ),
      'wp-backgroundpicker' =>
        array (
          'css' =>
            array (
              'wp-backgroundpicker-css' =>
                array (
                  'url' => 'wp-backgroundpicker/css/wp-backgroundpicker.css',
                  'path' => 'wp-backgroundpicker/css/wp-backgroundpicker.css',
                ),
            ),
          'js' =>
            array (
              'wp-backgroundpicker-js' =>
                array (
                  'url' => 'wp-backgroundpicker/js/wp-backgroundpicker.js',
                  'path' => 'wp-backgroundpicker/js/wp-backgroundpicker.js',
                ),
            ),
        ),
      'wp-bootstrap' =>
        array (
          'css' =>
            array (
              'wp-bootstrap-css' =>
                array (
                  'url' => 'wp-bootstrap/css/wp-bootstrap.css',
                  'path' => 'wp-bootstrap/css/wp-bootstrap.css',
                ),
            ),
          'js' =>
            array (
              'bootstrap-js' =>
                array (
                  'url' => 'wp-bootstrap/js/bootstrap.js',
                  'path' => 'wp-bootstrap/js/bootstrap.js',
                ),
            ),
        ),
      'wp-contact-info' =>
        array (
          'css' =>
            array (
              'wp-contact-info-css' =>
                array (
                  'url' => 'wp-contact-info/css/wp-contact-info.css',
                  'path' => 'wp-contact-info/css/wp-contact-info.css',
                ),
            ),
        ),
      'wp-fonts' =>
        array (
          'css' =>
            array (
              'wp-fonts-css' =>
                array (
                  'url' => 'wp-fonts/css/wp-fonts.css',
                  'path' => 'wp-fonts/css/wp-fonts.css',
                ),
            ),
          'js' =>
            array (
              'wp-fonts-js' =>
                array (
                  'url' => 'wp-fonts/js/wp-fonts.js',
                  'path' => 'wp-fonts/js/wp-fonts.js',
                ),
            ),
        ),
      'wp-fotorama' =>
        array (
          'css' =>
            array (
              'fotorama-css' =>
                array (
                  'url' => 'wp-fotorama/css/fotorama.css',
                  'path' => 'wp-fotorama/css/fotorama.css',
                ),
            ),
          'js' =>
            array (
              'fotorama-js' =>
                array (
                  'url' => 'wp-fotorama/js/fotorama.js',
                  'path' => 'wp-fotorama/js/fotorama.js',
                ),
            ),
        ),
      'wp-gradientpicker' =>
        array (
          'css' =>
            array (
              'wp-gradientpicker-css' =>
                array (
                  'url' => 'wp-gradientpicker/css/wp-gradientpicker.css',
                  'path' => 'wp-gradientpicker/css/wp-gradientpicker.css',
                ),
            ),
          'js' =>
            array (
              'wp-gradientpicker-js' =>
                array (
                  'url' => 'wp-gradientpicker/js/wp-gradientpicker.js',
                  'path' => 'wp-gradientpicker/js/wp-gradientpicker.js',
                ),
            ),
        ),
      'wp-icons' =>
        array (
          'css' =>
            array (
              'wp-icons-css' =>
                array (
                  'url' => 'wp-icons/css/wp-icons.css',
                  'path' => 'wp-icons/css/wp-icons.css',
                ),
            ),
          'js' =>
            array (
              'wp-icons-js' =>
                array (
                  'url' => 'wp-icons/js/wp-icons.js',
                  'path' => 'wp-icons/js/wp-icons.js',
                ),
            ),
        ),
      'wp-icons-front' =>
        array (
          'css' =>
            array (
              'wp-icons-front-css' =>
                array (
                  'url' => 'wp-icons-front/css/wp-icons-front.css',
                  'path' => 'wp-icons-front/css/wp-icons-front.css',
                ),
            ),
        ),
      'wp-loop' =>
        array (
          'js' =>
            array (
              'imageloaded-js' =>
                array (
                  'url' => 'wp-loop/js/imageloaded.js',
                  'path' => 'wp-loop/js/imageloaded.js',
                ),
              'wp-loop-js' =>
                array (
                  'url' => 'wp-loop/js/wp-loop.js',
                  'path' => 'wp-loop/js/wp-loop.js',
                ),
            ),
        ),
      'wp-media' =>
        array (
          'css' =>
            array (
              'wpmedia-css' =>
                array (
                  'url' => 'wp-media/css/wpmedia.css',
                  'path' => 'wp-media/css/wpmedia.css',
                ),
            ),
          'js' =>
            array (
              'wpmedia-js' =>
                array (
                  'url' => 'wp-media/js/wpmedia.js',
                  'path' => 'wp-media/js/wpmedia.js',
                ),
            ),
        ),
      'wp-multiplemedia' =>
        array (
          'css' =>
            array (
              'wp-multiplemedia-css' =>
                array (
                  'url' => 'wp-multiplemedia/css/wp-multiplemedia.css',
                  'path' => 'wp-multiplemedia/css/wp-multiplemedia.css',
                ),
            ),
          'js' =>
            array (
              'wp-multiplemedia-js' =>
                array (
                  'url' => 'wp-multiplemedia/js/wp-multiplemedia.js',
                  'path' => 'wp-multiplemedia/js/wp-multiplemedia.js',
                ),
            ),
        ),
      'wp-page' =>
        array (
          'css' =>
            array (
              'ginola-skins-css' =>
                array (
                  'url' => 'wp-page/css/ginola-skins.css',
                  'path' => 'wp-page/css/ginola-skins.css',
                ),
            ),
        ),
      'wp-printpdf' =>
        array (
          'js' =>
            array (
              'wp-printpdf-js' =>
                array (
                  'url' => 'wp-printpdf/js/wp-printpdf.js',
                  'path' => 'wp-printpdf/js/wp-printpdf.js',
                ),
            ),
        ),
      'wp-query' =>
        array (
          'css' =>
            array (
              'wp-query-css' =>
                array (
                  'url' => 'wp-query/css/wp-query.css',
                  'path' => 'wp-query/css/wp-query.css',
                ),
            ),
        ),
      'wp-termsboxes' =>
        array (
          'css' =>
            array (
              'wp-termboxes-css' =>
                array (
                  'url' => 'wp-termsboxes/css/wp-termboxes.css',
                  'path' => 'wp-termsboxes/css/wp-termboxes.css',
                ),
            ),
          'js' =>
            array (
              'wp-termsboxes-js' =>
                array (
                  'url' => 'wp-termsboxes/js/wp-termsboxes.js',
                  'path' => 'wp-termsboxes/js/wp-termsboxes.js',
                ),
            ),
        ),
      'wp-visualcomposer' =>
        array (
          'js' =>
            array (
              'wp-visualcomposer-js' =>
                array (
                  'url' => 'wp-visualcomposer/js/wp-visualcomposer.js',
                  'path' => 'wp-visualcomposer/js/wp-visualcomposer.js',
                ),
            ),
        ),
      'wp-visualcomposer-extra' =>
        array (
          'css' =>
            array (
              'wp-visualcomposer-extra-css' =>
                array (
                  'url' => 'wp-visualcomposer-extra/css/wp-visualcomposer-extra.css',
                  'path' => 'wp-visualcomposer-extra/css/wp-visualcomposer-extra.css',
                ),
            ),
        ),
      'wp-visualcomposer-form' =>
        array (
          'js' =>
            array (
              'wp-visualcomposer-form-js' =>
                array (
                  'url' => 'wp-visualcomposer-form/js/wp-visualcomposer-form.js',
                  'path' => 'wp-visualcomposer-form/js/wp-visualcomposer-form.js',
                ),
            ),
        ),
      'wp-visualcomposer-front' =>
        array (
          'js' =>
            array (
              'wp-visualcomposer-front-js' =>
                array (
                  'url' => 'wp-visualcomposer-front/js/wp-visualcomposer-front.js',
                  'path' => 'wp-visualcomposer-front/js/wp-visualcomposer-front.js',
                ),
            ),
        ),
      'wp-visualcomposer-iframe' =>
        array (
          'js' =>
            array (
              'wp-visualcomposer-iframe-js' =>
                array (
                  'url' => 'wp-visualcomposer-iframe/js/wp-visualcomposer-iframe.js',
                  'path' => 'wp-visualcomposer-iframe/js/wp-visualcomposer-iframe.js',
                ),
            ),
        ),
      'wp-widget' =>
        array (
          'css' =>
            array (
              'wp-widget-css' =>
                array (
                  'url' => 'wp-widget/css/wp-widget.css',
                  'path' => 'wp-widget/css/wp-widget.css',
                ),
            ),
          'js' =>
            array (
              'wp-widget-js' =>
                array (
                  'url' => 'wp-widget/js/wp-widget.js',
                  'path' => 'wp-widget/js/wp-widget.js',
                ),
            ),
        ),
    );

  }
}

